spring:
  application:
    name: cita

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:demo}
      model-name: gpt-5-mini
      temperature: 1.0
  ollama:
    embedding-model:
      base-url: http://localhost:11434
      model-name: embeddinggemma
      timeout: 120s
  milvus:
    host: localhost
    port: 19530
    collection-name: citarag
    dimension: 768 # EmbeddingGemma-300m dimension
