logging:
  level:
    com.zaxxer.hikari: DEBUG

spring:
  application:
    name: cita

  mvc:
    async:
      request-timeout: 3600000 # 60 minutes
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    url: jdbc:postgresql://localhost:5432/citarag
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: CitaRAG-HikariCP

server:
  tomcat:
    connection-timeout: 3600000 # 60 minutes
    keep-alive-timeout: 3600000 # 60 minutes
    max-swallow-size: -1

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:demo}
      model-name: gpt-5-mini
      temperature: 1.0

  milvus:
    host: 127.0.0.1
    port: 19530
    collection-name: citarag
    dimension: 1536 # text-embedding-3-small dimension
